version: "3.8"

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    environment:
      # lokalizacja wallet'u jest inna w kontenerze
      - TNS_ADMIN=/app/wallet
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties
      - ./src/main/resources/wallet:/app/wallet
      - ./documents:/app/documents
      - ./document-requests:/app/document-requests
    restart: unless-stopped
    networks:
      - spring-network

  frontend:
    build:
      context: ./mobywatel-web
      dockerfile: Dockerfile.dev
    container_name: mobywatel-frontend
    volumes:
      - ./mobywatel-web:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      # Remove VITE_API_BASE_URL since we'll use same origin
    restart: unless-stopped
    networks:
      - spring-network
    depends_on:
      - springboot-app

  nginx:
    image: nginx:alpine
    container_name: mobywatel-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - spring-network
    depends_on:
      - springboot-app
      - frontend

networks:
  spring-network:
    driver: bridge
