version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      # lokalizacja wallet'u jest inna w kontenerze
      - TNS_ADMIN=/app/wallet
      - JAVA_OPTS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=${PROFILE:-dev}
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties
      - ./src/main/resources/wallet:/app/wallet
    restart: unless-stopped
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge